---
title: "FA Icon Test"
output:
  html_document:
    theme: readable
    df_print: paged
    highlight: tango
    css: lab-instructions.css
    include:
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## icons package 

### Usage: 

```{r, eval=F}
remotes::install_github("mitchelloharawild/icons")
icons::download_fontawesome(version = "dev")
icons::fontawesome("twitter")
icons::fontawesome("github")
icons::fontawesome("home")
```

### Output Type

```{r}
ic <- icons::fontawesome("twitter")
class( ic )
str( ic )
```



```{r}
x <- paste0( "<a href='www.google.com'>  \n\n", as.character(ic), "\n\n</a>" )
x
```

```{r}
cat(x)
```



```{r, results="asis"}
as.character(ic)   # results="asis"
```

```{r, results="asis"}
cat( as.character(ic) )  # results="asis"
```


```{r, results="asis"}
add_icons <- function()
{
  cat( as.character( icons::fontawesome("twitter") ) )
  cat( as.character( icons::fontawesome("github")  ) )
  cat( as.character( icons::fontawesome("home")    ) )
}

add_icons()
```


## fontawesome package

### Usage: 

```{r, eval=F}
install.packages("fontawesome")
fontawesome::fa( name="github" )
fontawesome::fa( name="twitter" )
fontawesome::fa( name="home" )
```

### Output Type: 

```{r}
fa <- fontawesome::fa( name="github" )
class( fa )
str( fa )
```

```{r}
fa
```


```{r}
as.character(fa)
```

### results=asis

NO **results="asis"**. 

Prints as plain text after using paste(): 

```{r}
cat( paste0( '<a href="google.com">', fontawesome::fa( name="github" ), '</a>' ) )
```


<br>


ADD **results="asis"** 

Now it adds it to the RMD as HTML: 

```{r, results="asis"}
cat( paste0( '<a href="google.com">', fontawesome::fa( name="github" ), '</a>' ) )
```


<style>
h3{ upper-}
